CREATE TABLE player (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL);

INSERT INTO player (id, name) VALUES (1, 'Alice');
INSERT INTO player (id, name) VALUES (2, 'Bob');

CREATE TABLE game (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, player_one_id INT NOT NULL, progress VARCHAR(100) NOT NULL);
